<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Servicedetails extends Model
{
    use HasFactory;
    protected $fillable = [
         // 'Ventilation',
            // 'site_roomtemp',
            // 'site_cooling_temp_in',
            // 'site_cooling_temp_out',
            // 'site_cooling_pressure_in',
            // 'site_cooling_pressure_out',

            // 'detail_motor',
            // 'detail_cooler',
            // 'detail_topup',
            // 'detail_topup_liters',
            // 'detail_replace',
            // 'detail_replace_brand',
            // 'detail_overhaul_air',
            // 'detail_overhaul_motor',
            // 'detail_rewind',
            // 'detail_3000',
            // 'detail_6000',
            // 'detail_12000',
            // 'detail_other',

            'running_air_pressure_load',
            'running_air_pressure_unload',
            'running_air_pressure_normal',
            'running_os_pressure',
            'running_load',
            'running_air_temp_load',
            'running_air_temp_unload',
            'running_hourmeter_check',
            'running_current_load',
            'running_current_unload',
            'running_os_temp',
            'running_ambient_temp',
            'running_tc_temp',
            'running_load_count',
            'running_load_hour',
            'running_count',
            'running_suction_pressure',
            
            'setting_operation_local',
            'setting_operation_run_on',
            'setting_operation_run_load',
            'setting_group_link',
            'setting_group_panel',
            'setting_op_load',
            'setting_op_unload',
            'setting_op_auto',
            'setting_op_constant',
            'setting_phh',
            'setting_phl',
            'setting_ph',
            'setting_pl',
            'setting_pll',

            'meas_voltage_rs_on',
            'meas_voltage_rs_off',
            'meas_voltage_st_on',
            'meas_voltage_st_off',
            'meas_voltage_tr_on',
            'meas_voltage_tr_off',
            'meas_input_r_load',
            'meas_input_r_unload',
            'meas_input_s_load',
            'meas_input_s_unload',
            'meas_input_t_load',
            'meas_input_t_unload',
            'meas_motor_u_load',
            'meas_motor_u_unload',
            'meas_motor_v_load',
            'meas_motor_v_unload',
            'meas_motor_w_load',
            'meas_motor_w_unload',
            'meas_pipetemp',
            
            'functions_monitor',
            'functions_battery',
            'functions_sensor',
            'functions_ocr',
        
            'functions_timer',
            'functions_valve_open',
            'functions_valve_blow',
            'functions_valve_operate',
            'functions_thermal',
            'functions_magnetic',
            'functions_presssensor',
            'functions_tempsensor',
            'functions_pressswitch',
            'functions_flowswitch',
            'dischargev/v',

            'insulation_main_u1v1',
            'insulation_main_v1w1',
            'insulation_main_w1u1',
            'insulation_main_u1u2',
            'insulation_main_v1v2',
            'insulation_main_w1w2',
            'insulation_main_u1e',
            'insulation_main_v1e',
            'insulation_main_w1e',
            'insulation_fan_u1v1',
            'insulation_fan_v1w1',
            'insulation_fan_w1u1',
            'insulation_fan_u1e',
            'insulation_fan_v1e',
            'insulation_fan_w1e',

            'Type',
            'dryer_maker',
            'dryer_model',
            'dryer_sn',
            'dryer_dew',
            'dryer_inlet',

            'filter_maker',
             
            'maint_suction',
            'maint_oilfiter',
            'maint_oilseparator',
            'maint_oil',
            'maint_drainseparator',
            'maint_motorgrease',
            'maint_autoblowoff',
            'maint_capacityvav',
            'maint_presscontvav',
            'maint_presskeepvav',
            'maint_thermovav',
            'maint_oillevel',
            'maint_oilrecovery',
            'maint_belt',
            'maint_aftercooler',
            'maint_oilcooler',
            'maint_mainmotor',
            'maint_mecoilseal',
            'maint_fanmotor',
            'maint_airend',
            'maint_bearingair',
            'maint_bearingmotor',
            'maint_gauge',
            'maint_magnetic',
            'maint_sensor',
            'maint_maininv',
            'maint_faninv',
            'maint_leakage',
            'comment_compressor_normal',
            'comment_compressor_abnormal',
    ];
}
